### ISSUE TITLE
cannot get mesa to work

### ISSUE THREAD

**Issue by krnlyng** [natinusala/painless-linux#20]
Hi,

Can you give details about which build configurations and other settings or possible changes you made to mesa?

I tried to replicate everything you have here but mesa fails with:
```
[  998.829421] nouveau 57000000.gpu: gr: DATA_ERROR 00000003 [INVALID_OPERATION] ch 4 [04001bf000 kscreenlocker_g[2473]] subc 0 class b197 mthd 19d0 data 0000003f
[  998.829460] nouveau 57000000.gpu: gr: DATA_ERROR 0000009c [] ch 4 [04001bf000 kscreenlocker_g[2473]] subc 0 class b197 mthd 17e0 data 00000004
[  998.829494] nouveau 57000000.gpu: gr: DATA_ERROR 0000009c [] ch 4 [04001bf000 kscreenlocker_g[2473]] subc 0 class b197 mthd 17e0 data 00000004
[  998.829528] nouveau 57000000.gpu: gr: DATA_ERROR 0000009c [] ch 4 [04001bf000 kscreenlocker_g[2473]] subc 0 class b197 mthd 17e0 data 00000006
```

gnome-shell doesn't display anything and plasma only very limited graphics (almost nothing but a white bar)

thanks!

I did manage to rebase the switch linux kernel on top of 5.0.0-rc4 but that has similar/the same errors.

**Comment by natinusala** [comment]
Hey, you should use this as a base for mesa : https://github.com/lakka-switch/Lakka-LibreELEC/blob/master/packages/graphics/mesa/package.mk

**Comment by krnlyng** [comment]
you don't have the PKGBUILD file for arch linux still somewhere by any chance?
but thanks i will take a look at the lakka package

**Comment by natinusala** [comment]
Sorry I don't have a PKGBUILD

**Comment by krnlyng** [comment]
i got it to work by using 18.3.1 mesa instead of the master branch.

unfortunately games still run slow even though i've changed the gpu frequency to 768MHz, is there something else i need to tweak to get full performance in arch linux?

**Comment by natinusala** [comment]
Not much I'm afraid

**Comment by krnlyng** [comment]
the frequency scaling in my rebased kernel did not work properly, it works reasonably well with 4.xx, thx
