### ISSUE TITLE
Timeout waiting for hardware interrupt

### ISSUE THREAD

**Issue by jonyluke** [natinusala/painless-linux#21]
It does not boot and it is in a loop with

`mmc0: Timeout waiting for hardware interrupt`

**Comment by jonyluke** [comment]
![347a2951-12c9-4eed-a63a-a9d653be2fae](https://user-images.githubusercontent.com/9436549/53300349-26b87600-3846-11e9-9113-47c9a99749dd.jpg)

**Comment by natinusala** [comment]
There's a new kernel coming soon that will greatly improve boot rate
