### ISSUE TITLE
Is this still the best way to boot Linux on the Switch? 

### ISSUE THREAD

**Issue by UnicornsOnLSD** [natinusala/painless-linux#22]
Hi, sorry for bringing back a (seemingly) dead project.

There isn't much information on booting Linux (other than Lakka) on the Switch. Search results bring up outdated videos and news articles.

Is this still the best, most up to date way to boot Linux?

**Comment by natinusala** [comment]
Booting Linux is easy, what you are seeking for is a distribution. AFAIK there is none apart from this one and Lakka. You can craft one manually from the Arch rootfs though.
