### ISSUE TITLE
SDXC Issues

### ISSUE THREAD

**Issue by NO-ob** [natinusala/painless-linux#3]
Arch has an issue on boot reading sdxc cards and gets stuck in a loop there was a fix in this gbatemp thread https://gbatemp.net/threads/quick-tuto-how-to-boot-linux-on-your-switch.501918/page-41 

'This kernel includes a "fix" for the "Timeout waiting on hardware interrupt" error and has working WIFI.
Simply remove the .zip extension from the end of the file and place it in linux/arch/arm64/boot/ (NOT ON YOUR SDCARD)
Example: /home/USERNAME/switch-linux/linux/arch/arm64/boot/

(If you are using SoulCiphers precompiled binaries just drop it in /home/USERNAME/shofel2_linux/kernel/)

Remember, you have to reboot at least once to get WIFI working. '

This is the file: https://gbatemp.net/attachments/image-gz-zip.121538/ 

Is there a way i can use that file with your build to be able to boot? It gets stuck saying 'Timeout for hardware interupt and then dumps the sdhci register it will loop this then stop after about 15 minutes and not do anything else

**Comment by natinusala** [comment]
After burning the image on the SD card you'll see that it contains a FAT32 partition with a `boot` folder in it. Put your new Image.gz file instead of the one already present here, and boot. Report here if it fixed your issue !

**Comment by NO-ob** [comment]
Okay thank you I'm about to sleep but I'll test it out first thing in the morning

**Comment by NO-ob** [comment]
It doesn't boot at all the shell script completes and the switch does nothing

**Comment by NO-ob** [comment]
okay it booted after redownloading but only for about 3 seconds and now wont boot again, it wasnt enough time to read what it said on the screen

**Comment by ckurtz22** [comment]
having the same issue as NO-ob. After replacing the image.gz, it first booted up and went past the alarm login, then it immediately rebooted back to rcm, and every time I try to boot it now it goes for about 2 seconds, throws a bunch of errors, then back to rcm

**Comment by NO-ob** [comment]
After putting the sd back into my computer it appears the ext4 partition is being corrupted or something its filesystem is being shown as uknown in gparted and cannot be mounted using disks

**Comment by NO-ob** [comment]
I have discovered that formatting the sdxc card to fat32 in gparted makes the card work without updating the switch firmware in horizon. This didn't work when i tried formatting the card in windows

**Comment by natinusala** [comment]
Did you try to burn the image again and replace the kernel again ? If the ext4 partition was corrupted, it's no surprise it won't work.

**Comment by NO-ob** [comment]
yeah i think it's that image which corrupts the ext4 partition I tried flashing the img to the sd card 3 times and upon boot it had the same result of currupting the partition. I'll just use another sd card ive probably got one somewhere

**Comment by ckurtz22** [comment]
When you boot it for the first time with the patched Kernel, whatever it does on the first boot to resize root or whatever is corrupting the ext4 partition. Can we just disable that part since it seems super unnecessary and obviously isn't working properly for SDXC since it is just corrupting it.

**Comment by natinusala** [comment]
You can disable auto expansion by burning the image again and deleting the /.resize-me (or whatever it's called) file before first boot

**Comment by NO-ob** [comment]
thankyou seems to be working perfectly now
