### ISSUE TITLE
Mac OS X support

### ISSUE THREAD

**Issue by k2cCreations** [natinusala/painless-linux#5]
When I am running the Linuc MacOs Boot I get this:

Scotts-MBP:uhf ScottG$ /Users/ScottG/Desktop/uhf/linux-macos-boot.sh 
Put your Switch in RCM mode now
Traceback (most recent call last):
  File "shofel2/shofel2.py", line 246, in <module>
    rcm = RCM()
  File "shofel2/shofel2.py", line 50, in __init__
    fds_before = get_fds()
  File "shofel2/shofel2.py", line 37, in get_fds
    return set(int(i) for i in os.listdir("/proc/self/fd"))
FileNotFoundError: [Errno 2] No such file or directory: '/proc/self/fd'

**Comment by natinusala** [comment]
Mac OS support is broken right now. Shofel2 needs to be updated.

**Comment by k2cCreations** [comment]
Well I feel less stupid haha thanks. I cant wait. I appreciate your time and work

**Comment by natinusala** [comment]
I keep this issue open to keep track of the Mac OS implementation

**Comment by natinusala** [comment]
Fixed by #7
