### ISSUE TITLE
Error While Booting

### ISSUE THREAD

**Issue by Zenith222** [natinusala/painless-linux#9]
This is the error I get. It shows up, followed by more text. It keeps repeating itself in a cycle.

`mmc0: Timeout waiting for hardware interrupt.`

I know this is brief. This was showing up on the Switch's screen. It had the four tuxes. It seems to be an SD card issue but I don't know what I did wrong. It is a 64GB Samsung card, so capacity is not the issue.
Any idea what is going on?

**Comment by Zenith222** [comment]
I know this is brief. This was showing up on the Switch's screen. It had the four tuxes. It seems to be an SD card issue but I don't know what I did wrong.

**Comment by natinusala** [comment]
Your SD card is not correctly setup. Is it a SDXC card ?

**Comment by Zenith222** [comment]
Yes, it is Micro SDXC

**Comment by natinusala** [comment]
Wait for a patch then, it's not supported yet

**Comment by Zenith222** [comment]
Oh, which type should I use then? I notice you mentioned that 128 GB cards do not work. Is it more specifically SDXC cards that don't work?

**Comment by natinusala** [comment]
Yes, 128Gb cards are SDXC. You should use a SD or SDHC

**Comment by Zenith222** [comment]
Well, as it turns out I don't have any SDHC cards that are above 8gb. Oh well, I'll wait for that support to come before I try again.
